# Generated by Django 4.0.5 on 2022-06-24 07:28

import My_Music_App.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_album_id_alter_album_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[My_Music_App.validators.username_validator, django.core.validators.MinLengthValidator(2)], verbose_name='Username'),
        ),
    ]
