# Generated by Django 4.0.5 on 2022-06-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_album_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', max_length=400, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(max_length=400, verbose_name='Image URL'),
        ),
    ]
