# Generated by Django 4.0.5 on 2022-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_profile_image_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Profile image'),
        ),
    ]
